### ISSUE TITLE
How can I change color of active and inactive color ?

### ISSUE THREAD

**Issue by Sihak** [ShubhamLolge/floating_tabbar#2]
Since my project need to follow the core design, so I want to change color of my tab's label, but I cannot find anywhere to change its color. Anyone know how to change it please help me ?

**Comment by ShubhamLolge** [comment]
> Since my project need to follow the core design, so I want to change color of my tab's label, but I cannot find anywhere to change its color. Anyone know how to change it please help me ?

Hello Sihak,

Thank you for raising an issue about the incompatibility noticed in the package, I have fixed the code and added two new parameters for FloatingTabBar which will solve your problem, "activeColor" and "inactiveColor" using these you can manipulate the color of tabs also label colors, and even if you don't pass value to these parameters, the widget will take it from app theme.
Also, check out the TabItem model it has a parameter for showing a badge count on your tabs across platforms, also check the "titleTapNavigationRouteWidget" parameter, provide the landing home route as a value, and on-click on the title on navigation rail control will move to that route (for web).

**Comment by ShubhamLolge** [comment]
As I have provided a solution for the issue in the form of a hotfix I am closing this issue.
