### ISSUE TITLE
Not show on left side

### ISSUE THREAD

**Issue by function2000** [ShubhamLolge/floating_tabbar#4]
This is a nice plugin, but I tried, and it is not show on left side:
I already set: useNautics: true,
![image](https://user-images.githubusercontent.com/4005363/199144201-34101dcb-9ea2-4980-8999-1422a59262fb.png)

**Comment by ShubhamLolge** [comment]
Hey @function2000,
Thank you for reaching out with the issue, I'd love to help you solve this, from the screenshot, you provided I can see that the screen is large in size but the navigation widget is still in small-screen mode, to solve this issue I want you to provide the code that you wrote that is resulting in this output, and one more piece of information, the output is in what platform you are checking the app.

**Comment by ShubhamLolge** [comment]
Closing this defect as there was no further communication.

**Comment by michalss** [comment]
same here
