### ISSUE TITLE
Sidebar not Tabbed

### ISSUE THREAD

**Issue by michalss** [ShubhamLolge/floating_tabbar#6]
Hi how can i force to have reall sidebar. Not as tabbed. Im trying Android and it still on bottom as Tabbed, but i want to have it as sidebar on left side..

I just used your example code from pub.dev.. 1:1

**Comment by ShubhamLolge** [comment]
Hi @michalss apologies for the late reply for the issue you are facing but I wanted to confirm the actual interface you're trying to achieve, is it like this you wanted to achieve or something else,
<img width="474" alt="image" src="https://github.com/ShubhamLolge/floating_tabbar/assets/75387392/c071f76c-0a28-42cb-8715-63ce537cc441">

if this what you wanted then you need to use the widget called 'Nautics' and use the widget inside the 'Row' widget with the 
child other than nautics wrapped with 'Expandable' widget then you'll achieve the exact engagement. 

And if you need any more help from me I am available to connect let me know I am more than happy to help.

**Comment by ShubhamLolge** [comment]
Hi @michalss, I hope your issue is resolved by the use of Nautics widget with the direction I provided, if you still face any problems you can reopen the issue I will resolve it.

Thanks.
