### ISSUE TITLE
can't change children count of TopTabbar dynamically

### ISSUE THREAD

**Issue by jessenee** [ShubhamLolge/floating_tabbar#7]
can't change children count of TopTabbar dynamically, will cause error: 
Controller's length property does not match the number of children present in TabBarView's children property.

TopTabbar's controller cannot be customized.

**Comment by ShubhamLolge** [comment]
Hi @jessenee thank you for waiting, I get the point you are trying to make here, allow me some time to fix it and let me get back to you with the fix.

**Comment by ShubhamLolge** [comment]
Hi @jessenee, I fixed the code as well as pushed a minor release, thanks for reporting the issue this helps in improving the package.
