### ISSUE TITLE
no onTap for TopTabbar children

### ISSUE THREAD

**Issue by jessenee** [ShubhamLolge/floating_tabbar#8]
no onTap triggered for TopTabbar child TabItem, it's needed to remember last selected

**Comment by ShubhamLolge** [comment]
Hi @jessenee, I get the point you are trying to make here, allow me some time to fix it and let me get back to you with the fix.

**Comment by ShubhamLolge** [comment]
Hi @jessenee I have fixed the issue and pushed a minor release for the same, thanks for reporting the issue this helps improve the package.
